// Auto-generated by scrape.js — 2026-05-20T23:51:30.484Z
// Sources: r/Dreams, r/LucidDreaming, r/Nightmares (top posts, past year)
// Posts analyzed: 1298 | Posts matched: 847

// Raw global theme scores (used for bubble chart)
var redditGlobal = { deceased: 543, chased: 201, flying: 271, falling: 359, teeth: 115, ancestors: 20, exam: 458, divine: 453, paralysis: 316, lucid: 1531, apocalypse: 80, celebrity: 33 };
